// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npwxxmboagkouafjwhhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wd3h4bWJvYWdrb3VhZmp3aGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODUxNjYsImV4cCI6MjA2MDg2MTE2Nn0.zTfwVxDurhs0F32ILpcRc3mCnwh1kkSYd-oYJ42sNGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);